name: Create a chore
description: Changes to build processes, tools, refactors.
labels: ['chore', 'triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this chore request!

  - type: input
    id: description
    attributes:
      label: Describe the chore
      description: A clear and concise description of what the chore is.
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
